name: Release Azure Policies package

on:
  push:
    tags:
      - azure-policies-*

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  azure-policies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org
          always-auth: true

      - name: Build Azure Policies
        run: |
          cd vendor-azure
          make build publish
